{{- $fullName := include "codeserver.fullname" . -}}
{{- $host := printf "%s.%s" .Release.Name .Values.ingress.domain -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
{{ include "codeserver.labels" . | indent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    ingress.kubernetes.io/auth-type: forward
    ingress.kubernetes.io/auth-url: http://ide-code-server-k8s.{{ .Release.Namespace }}.svc.cluster.local:8080/auth
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
  - host: {{ $host }}
    http:
      paths:
      - backend:
          serviceName: {{ $fullName }}
          servicePort: http
{{- end }}
