{{- $fullName := include "codeserver.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
{{ include "codeserver.labels" . | indent 4 }}
  annotations:
    kubernetes.io/ingress.class: traefik
    ingress.kubernetes.io/auth-type: forward
    ingress.kubernetes.io/auth-url: https://ide-code-server-k8s.{{ .Release.Namespace }}.svc.cluster.local:8080/auth
spec:
  tls:
  - secretName: tls-secret  
  rules:
  - host: {{ printf "%s.%s" .Release.Name .Values.ingress.domain }}
    http:
      paths:
      - backend:
          serviceName: {{ $fullName }}
          servicePort: http
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-custom-ingress
  labels:
{{ include "codeserver.labels" . | indent 4 }}
  annotations:
    kubernetes.io/ingress.class: traefik
    ingress.kubernetes.io/auth-type: forward
    ingress.kubernetes.io/auth-url: https://ide-code-server-k8s.{{ .Release.Namespace }}.svc.cluster.local:8080/auth
spec:
  tls:
  - secretName: tls-secret  
  rules:
  - host: server-{{ printf "%s.%s" .Release.Name .Values.ingress.domain }}
    http:
      paths:
      - backend:
          serviceName: {{ $fullName }}-custom-service
          servicePort: http2
