apiVersion: v1
kind: Service
metadata:
  name: {{ include "codeserver.fullname" . }}
  labels:
{{ include "codeserver.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "codeserver.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
