apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: codeservers.coder.com
spec:
  group: coder.com
  names:
    kind: CodeServer
    listKind: CodeServerList
    plural: codeservers
    singular: codeserver
  scope: Namespaced
  subresources:
    status: {}
  versions:
  - name: v1alpha1
    served: true
    storage: true