apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-server
spec:
  replicas: 1
  selector:
    matchLabels:
      name: code-server
  template:
    metadata:
      labels:
        name: code-server
    spec:
      serviceAccountName: code-server
      containers:
        - name: code-server
          # Replace this with the built image name
          image: atgracey/code-server-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "code-server"
