apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-operator" .Release.Name }}
  labels:
{{ include "code_server_k8s.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "code_server_k8s.name" . }}
      app.kubernetes.io/instance: {{ printf "%s-operator" .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "code_server_k8s.name" . }}
        app.kubernetes.io/instance: {{ printf "%s-operator" .Release.Name }}
    spec:
      serviceAccountName: {{ printf "%s-sa" .Chart.Name }}
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ printf "%s-operator" .Chart.Name }}
          image: "{{ printf "atgracey/code-server-operator:%s" {{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: WATCH_NAMESPACE
              value: {{ .Release.Namespace }}
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "code-server"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
